// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOv5Eq0OVidGOUrBKgcvfDBZ8krRzdsM',
    appId: '1:389836241024:web:25dcdfa5e71740381d0e65',
    messagingSenderId: '389836241024',
    projectId: 'chatapptute-18658',
    authDomain: 'chatapptute-18658.firebaseapp.com',
    storageBucket: 'chatapptute-18658.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDq2gkQaSVpyfebOy5nGmiTxHP3EzBVAc',
    appId: '1:389836241024:android:5fdc8b9a2dcfa04f1d0e65',
    messagingSenderId: '389836241024',
    projectId: 'chatapptute-18658',
    storageBucket: 'chatapptute-18658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wBlnLwfhQAbp8jaMR0yxoacXrGlmBbc',
    appId: '1:389836241024:ios:bfb9cac9f7b6c3b51d0e65',
    messagingSenderId: '389836241024',
    projectId: 'chatapptute-18658',
    storageBucket: 'chatapptute-18658.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wBlnLwfhQAbp8jaMR0yxoacXrGlmBbc',
    appId: '1:389836241024:ios:bfb9cac9f7b6c3b51d0e65',
    messagingSenderId: '389836241024',
    projectId: 'chatapptute-18658',
    storageBucket: 'chatapptute-18658.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvOv5Eq0OVidGOUrBKgcvfDBZ8krRzdsM',
    appId: '1:389836241024:web:ed858d960f6f30611d0e65',
    messagingSenderId: '389836241024',
    projectId: 'chatapptute-18658',
    authDomain: 'chatapptute-18658.firebaseapp.com',
    storageBucket: 'chatapptute-18658.appspot.com',
  );
}
